name: food_hub
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_onboarding_slider: ^1.0.11
  go_router: ^14.3.0
  flutter_svg: ^2.0.10+1
  get_it: ^8.0.0
  firebase_core: ^3.6.0
  dartz: ^0.10.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.4
  path_provider:
  firebase_auth: ^5.3.1
  flutter_styled_toast: ^2.2.1
  awesome_bottom_bar: ^1.2.4
  shared_preferences: ^2.3.2
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: 
  extended_image: ^9.0.3
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  url_launcher:
  easy_stepper: ^0.8.5+1
  flutter_stripe: ^11.2.0
  http: ^1.2.2
  dio: ^5.7.0
  flare_flutter: ^3.0.2
  lottie: ^3.1.3
  hydrated_bloc: ^9.1.5
  flutter_launcher_icons: ^0.14.1
 
 
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 23
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/icon/icon.png'
  
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/vector/
    - assets/image/
    - assets/lottie/
    - assets/icon/
    
